# Generated by Django 3.2.5 on 2021-07-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_backlog',
        ),
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
    ]
